USE [master]
GO

/****** Object:  Database [ECommerceApp]    Script Date: 19-03-20 20:18:05 ******/
CREATE DATABASE [ECommerceApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ECommerceApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ECommerceApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ECommerceApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ECommerceApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECommerceApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECommerceApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECommerceApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECommerceApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECommerceApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECommerceApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECommerceApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECommerceApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECommerceApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECommerceApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECommerceApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECommerceApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECommerceApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECommerceApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECommerceApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECommerceApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ECommerceApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECommerceApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECommerceApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECommerceApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECommerceApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECommerceApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECommerceApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECommerceApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ECommerceApp] SET  MULTI_USER 
GO

ALTER DATABASE [ECommerceApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECommerceApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ECommerceApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ECommerceApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ECommerceApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ECommerceApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ECommerceApp] SET  READ_WRITE 
GO



